all: bubble0 bubble1 insertion00 insertion0 insertion1 insertion2 insertion3 selection0 shaker0 shell0 shell1 keyCounter swift0 swift1 swift2 swift3 swift4 swift5 swift6 merge0 merge1 merge2 merge3 merge4

bubble0:  bubble0.c utils.h
	gcc -o 	bubble0 bubble0.c  --std=c99 -g 

bubble1: bubble1.c utils.h utils.c
	gcc -o bubble1 bubble1.c --std=c99 -g 
	
insertion00: insertion00.c utils.h utils.c
	gcc -o insertion00 utils.c insertion00.c utils.h --std=c99 -g 
insertion0: insertion0.c utils.h utils.c
	gcc -o insertion0 utils.c insertion0.c utils.h --std=c99 -g 

insertion1: insertion1.c utils.h utils.c
	gcc -o insertion1 utils.c insertion1.c utils.h --std=c99 -g 


insertion2: insertion2.c utils.h utils.c
	gcc -o insertion2 utils.c insertion2.c utils.h --std=c99 -g 

insertion3: insertion3.c utils.h utils.c
	gcc -o insertion3 utils.c insertion3.c utils.h --std=c99 -g 

selection0: selection0.c utils.h utils.c
	gcc -o selection0 utils.c selection0.c utils.h --std=c99 -g 

shaker0: shaker0.c utils.h utils.c
	gcc -o shaker0 utils.c shaker0.c utils.h --std=c99 -g 

shell0: shell0.c utils.h utils.c
	gcc -o shell0 utils.c shell0.c utils.h --std=c99 -g 

shell1: shell1.c utils.h utils.c
	gcc -o shell1 utils.c shell1.c utils.h --std=c99 -g 
keyCounter: keyCounter.c utils.h utils.c
	gcc -o keyCounter utils.c keyCounter.c utils.h --std=c99 -g 
swift0: swift0.c utils.h utils.c
	gcc -o swift0 utils.c swift0.c utils.h --std=c99 -g 
swift1: swift1.c utils.h utils.c
	gcc -o swift1 utils.c swift1.c utils.h --std=c99 -g 
swift2: swift2.c utils.h utils.c stack.c
	gcc -o swift2 swift2.c utils.c stack.c utils.h --std=c99 -g 
swift3: swift3.c utils.h utils.c stack.c
	gcc -o swift3 swift3.c utils.c stack.c utils.h --std=c99 -g 
swift4: swift4.c utils.h utils.c stack.c
	gcc -o swift4 swift4.c utils.c stack.c utils.h --std=c99 -g 
swift5: swift5.c utils.h utils.c stack.c
	gcc -o swift5 swift5.c utils.c stack.c utils.h --std=c99 -g 
swift6: swift6.c utils.h utils.c stack.c
	gcc -o swift6 swift6.c utils.c stack.c utils.h --std=c99 -g 
merge0: merge0.c utils.h utils.c stack.c
	gcc -o merge0 merge0.c utils.c stack.c utils.h --std=c99 -g 
merge1: merge1.c utils.h utils.c stack.c
	gcc -o merge1 merge1.c utils.c stack.c utils.h --std=c99 -g 
merge2: merge2.c utils.h utils.c stack.c
	gcc -o merge2 merge2.c utils.c stack.c utils.h --std=c99 -g 
merge3: merge3.c utils.h utils.c stack.c
	gcc -o merge3 merge3.c utils.c stack.c utils.h --std=c99 -g 
merge4: merge4.c utils.h utils.c stack.c
	gcc -o merge4 merge4.c utils.c stack.c utils.h --std=c99 -g 
clean:
	rm -f bubble0 bubble1 insertion00 insertion0 insertion1 insertion2 insertion3 selection0 shaker0 shell0 shell1 keyCounter swift0 swift1 swift2 swift3 swift4 swift5 swift6 merge0 merge1 merge2 merge3 merge4
